formdata = {
    'deposittype': "",
    'dates': {},
    'dissertation': {
        'degreename': {
            'EDD': 'Doctor of Education (EDD)',
            'DA': 'Doctor of Arts (DA)',
            'DMA': 'Doctor of Musical Arts (DMA)',
            'PhD': 'Doctor of Philosophy (PHD)'
        },
        'degreetype': {
            'dissertation': 'Dissertation',
            'essay': 'Doctoral Essay',
            'treatise': 'Doctoral Treatise',
            'lecture': 'Lecture Recital Essay'
        }
    },
    'masters': {
        'degreename': {
            'MSArch': 'Master of Architecture (MSArch)',
            'MA': 'Master of Arts (MA)',
            'DMA': 'Master of Engineering (ME)',
            'MFA': 'Master of Fine Arts (MFA)',
            'MM': 'Master of Music (MM)',
            'MSc': 'Master of Science (MS)',
            'MSEd': 'Master of Education (MSEd)'

        }
    },
    'languages': {
        'es': 'Spanish',
        'ar': 'Arabic',
        'zh': 'Chinese',
        'fr': 'French',
        'de': 'German',
        'hi': 'Hindi',
        'it': 'Italian',
        'ja': 'Japanese',
        'ko': 'Korean',
        'pt': 'Portuguese',
        'ru': 'Russian'
    },
    'departments': {
        'Art History (Arts and Sciences)',
        'Biology',
        'Biology (Arts and Sciences)',
        'Chemistry',
        'Chemistry (Arts and Sciences)',
        'Computer Science',
        'Computer Science (Arts and Sciences)',
        'English',
        'English (Arts and Sciences)',
        'Geography (Arts and Sciences)',
        'History',
        'History (Arts and Sciences)',
        'International Studies',
        'International Studies (Arts and Sciences)',
        'Mathematics',
        'Mathematics (Arts and Sciences)',
        'Modern Languages and Literatures (Arts and Sciences)',
        'Philosophy',
        'Philosophy (Arts and Sciences)',
        'Physics',
        'Physics (Arts and Sciences)',
        'Physics Physiology and Biophysics',
        'Political Science',
        'Psychology',
        'Psychology (Arts and Sciences)',
        'Sociology',
        'Sociology (Arts and Sciences)',
        'Biochemistry and Molecular Biology',
        'Biochemistry and Molecular Biology (Medicine)',
        'Biomedical Engineering',
        'Biomedical Engineering (Engineering)',
        'Civil, Architectural and Environmental Engineering (Engineering)',
        'Electrical and Computer Engineering',
        'Electrical and Computer Engineering (Engineering)',
        'Industrial Engineering',
        'Industrial Engineering (Engineering)',
        'Mechanical and Aerospace Engineering',
        'Mechanical Engineering',
        'Mechanical Engineering (Engineering)',
        'Biology and Living Resources',
        'Clinical Psychology',
        'Counseling Psychology',
        'Developmental Psychology',
        'Foreign Languages and Literatures',
        'French',
        'Latin American and Caribbean Studies',
        'Latin American Studies (Arts and Sciences)',
        'Liberal Studies (Arts and Sciences)',
        'Management Psychology',
        'Spanish',
        'Zoology',
        'Civil and Architectural Engineering',
        'Ergonomics',
        'Ergonomics (Engineering)',
        'Music',
        'Music Choral and Voice',
        'Music Composition',
        'Music Conducting',
        'Music Education',
        'Music Literature',
        'Music Performance',
        'Performance (Music)',
        'School of Music Music Performance',
        'Ecosystem Science and Policy (Graduate)',
        'Interdepartmental Studies',
        'Interdisciplinary Studies (Graduate)',
        'Microbiology and Immunology',
        'Microbiology and Immunology (Medicine)',
        'Cancer Biology (Medicine)',
        'Cell Biology and Anatomy',
        'Cell Biology and Anatomy (Medicine)',
        'Cellular and Molecular Biology',
        'Epidemiology (Medicine)',
        'Epidemiology and Public Health',
        'Human Genetics and Genomics (Medicine)',
        'Interdisciplinary Biomedical Studies (Medicine)',
        'Molecular Cell and Developmental Biology',
        'Molecular Cell and Developmental Biology (Medicine)',
        'Neuroscience',
        'Neuroscience (Medicine)',
        'Pharmacology',
        'Molecular and Cellular Pharmacology',
        'Molecular and Cellular Pharmacology (Medicine)',
        'Physiology and Biophysics',
        'Physiology and Biophysics (Medicine)',
        'Applied Marine Physics (Marine)',
        'Applied Marine Physics/Ocean Engineering',
        'Chemical Oceanography',
        'Marine Affairs and Policy (Marine)',
        'Marine and Atmospheric Chemistry',
        'Marine and Atmospheric Chemistry (Marine)',
        'Marine Biology and Fisheries',
        'Marine Biology and Fisheries (Marine)',
        'Marine Geology and Geophysics',
        'Marine Geology and Geophysics (Marine)',
        'Marine Science',
        'Meteorology and Physical Oceanography',
        'Meteorology and Physical Oceanography (Marine)',
        'Oceanography',
        'Atmospheric Science',
        'Marine Biology and Ecology (Marine)',
        'Marine Ecosystems and Society (Marine)',
        'Accounting (Business)',
        'Business Administration',
        'Economics',
        'Economics (Business)',
        'Finance (Business)',
        'Management (Business)',
        'Management Science',
        'Management Science (Business)',
        'Marketing (Business)',
        'Educational and Psychological Studies (Education)',
        'Architecture (Architecture)',
        'Computer Information Systems',
        'Communication',
        'Communication (Communication)',
        'Motion Pictures (Communication)',
        'Cinema and Interactive Media (Communication)',
        'Communication Studies (Communication)',
        'Public Relations (Communication)',
        'Kinesiology and Sport Sciences (Education)',
        'Teaching and Learning',
        'Teaching and Learning (Education)',
        'Education',
        'Educational Administration',
        'Educational Leadership',
        'Educational Psychology',
        'Educational Research',
        'Elementary Education',
        'Exercise and Sport Sciences',
        'Higher Education',
        'Reading',
        'Reading and Learning Disabilities',
        'Secondary Education',
        'Special Education',
        'Music Education and Music Therapy (Music)',
        'Instrumental Performance (Music)',
        'Keyboard Performance (Music)',
        'Musicology (Music)',
        'Music Studio and Jazz',
        'Studio Music and Jazz (Music)',
        'Music Theory and Composition',
        'Music Theory and Composition (Music)',
        'Vocal Performance (Music)',
        'Nursing',
        'Nursing (Nursing)',
        'Biostatistics (Medicine)',
        'Public Health Sciences (Medicine)',
        'Physical Therapy',
        'Physical Therapy (Medicine)',
    },
    'topics': {
        'Fine and Performing Arts': {
            'Art criticism': '0365',
            'Art history': '0377',
            'Cinematography': '0435',
            'Dance': '0378',
            'Design': '0389',
            'Fashion': '0200',
            'Film studies': '0900',
            'Fine arts': '0357',
            'Music': '0413',
            'Music history': '0210',
            'Music theory': '0223',
            'Musical composition': '0216',
            'Musical performances': '0943',
            'Performing arts': '0641',
            'Theater': '0465',
            'Theater history': '0644'
        }
    }
}