formdata = {
    'deposittype': "",
    'dates': {},
    'dissertation': {
        'degreename': {
            'EDD': 'Doctor of Education (EDD)',
            'DA': 'Doctor of Arts (DA)',
            'DMA': 'Doctor of Musical Arts (DMA)',
            'PhD': 'Doctor of Philosophy (PHD)'
        },
        'degreetype': {
            'dissertation': 'Dissertation',
            'essay': 'Doctoral Essay',
            'treatise': 'Doctoral Treatise',
            'lecture': 'Lecture Recital Essay'
        }
    },
    'masters': {
        'degreename': {
            'MSArch': 'Master of Architecture (MSArch)',
            'MA': 'Master of Arts (MA)',
            'DMA': 'Master of Engineering (ME)',
            'MFA': 'Master of Fine Arts (MFA)',
            'MM': 'Master of Music (MM)',
            'MSc': 'Master of Science (MS)',
            'MSEd': 'Master of Education (MSEd)'

        }
    },
    'languages': {
        'es': 'Spanish',
        'ar': 'Arabic',
        'zh': 'Chinese',
        'fr': 'French',
        'de': 'German',
        'hi': 'Hindi',
        'it': 'Italian',
        'ja': 'Japanese',
        'ko': 'Korean',
        'pt': 'Portuguese',
        'ru': 'Russian'
    },
    'departments': [
        'Accounting (Business)',
        'Applied Marine Physics (Marine)',
        'Architecture (Architecture)',
        'Art History (Arts and Sciences)',
        'Biochemistry and Molecular Biology (Medicine)',
        'Biology (Arts and Sciences)',
        'Biomedical Engineering (Engineering)',
        'Biostatistics (Medicine)',
        'Cancer Biology (Medicine)',
        'Cell Biology and Anatomy (Medicine)',
        'Chemistry (Arts and Sciences)',
        'Cinema and Interactive Media (Communication)',
        'Civil, Architectural and Environmental Engineering (Engineering)',
        'Communication (Communication)',
        'Computer Science (Arts and Sciences)',
        'Economics (Business)',
        'Ecosystem Science and Policy (Graduate)',
        'Educational and Psychological Studies (Education)',
        'Electrical and Computer Engineering (Engineering)',
        'English (Arts and Sciences)',
        'Epidemiology (Medicine)',
        'Ergonomics (Engineering)',
        'Finance (Business)',
        'Geography (Arts and Sciences)',
        'History (Arts and Sciences)',
        'Human Genetics and Genomics (Medicine)',
        'Industrial Engineering (Engineering)',
        'Instrumental Performance (Music)',
        'Interdisciplinary Biomedical Studies (Medicine)',
        'Interdisciplinary Studies (Graduate)',
        'International Studies (Arts and Sciences)',
        'Keyboard Performance (Music)',
        'Kinesiology and Sport Sciences (Education)',
        'Latin American Studies (Arts and Sciences)',
        'Liberal Studies (Arts and Sciences)',
        'Management Science (Business)',
        'Marine and Atmospheric Chemistry (Marine)',
        'Marine Biology and Ecology (Marine)',
        'Marine Biology and Fisheries (Marine)',
        'Marine Ecosystems and Society (Marine)',
        'Marine Geology and Geophysics (Marine)',
        'Marketing (Business)',
        'Mathematics (Arts and Sciences)',
        'Mechanical Engineering (Engineering)',
        'Meteorology and Physical Oceanography (Marine)',
        'Microbiology and Immunology (Medicine)',
        'Modern Languages and Literatures (Arts and Sciences)',
        'Molecular and Cellular Pharmacology (Medicine)',
        'Molecular Cell and Developmental Biology (Medicine)',
        'Motion Pictures (Communication)',
        'Music Education and Music Therapy (Music)',
        'Music Theory and Composition (Music)',
        'Musicology (Music)',
        'Neuroscience (Medicine)',
        'Nursing (Nursing)',
        'Operations Management (Business)',
        'Organizational Behavior (Business)',
        'Philosophy (Arts and Sciences)',
        'Physical Therapy (Medicine)',
        'Physics (Arts and Sciences)',
        'Physiology and Biophysics (Medicine)',
        'Psychology (Arts and Sciences)',
        'Public Health Sciences (Medicine)',
        'Sociology (Arts and Sciences)',
        'Strategy/International Business (Business)',
        'Studio Music and Jazz (Music)',
        'Teaching and Learning (Education)',
        'Vocal Performance (Music)'
    ],
    'topics': {
        'Fine and Performing Arts': {
            'Art criticism': '0365',
            'Art history': '0377',
            'Cinematography': '0435',
            'Dance': '0378',
            'Design': '0389',
            'Fashion': '0200',
            'Film studies': '0900',
            'Fine arts': '0357',
            'Music': '0413',
            'Music history': '0210',
            'Music theory': '0223',
            'Musical composition': '0216',
            'Musical performances': '0943',
            'Performing arts': '0641',
            'Theater': '0465',
            'Theater history': '0644'
        }
    }
}
