formdata = {
    'deposittype': "",
    'dates': {},
    'dissertation': {
        'degreename': {
            'Doctor of Musical Arts (DMA)',
            'Doctor of Education (EDD)',
            'Doctor of Philosophy (PhD)'
        },
        'degreetype': {
            'dissertation': 'Dissertation',
            'essay': 'Doctoral Essay',
            'treatise': 'Doctoral Treatise',
            'lecture': 'Lecture Recital Essay'
        },
        'degrees': {
            'Applied Marine Physics': 'Applied Marine Physics (RSMAS)',
            'Atmospheric Sciences ': 'Atmospheric Sciences (RSMAS)',
            'Biochemistry and Molecular Biology': 'Biochemistry and Molecular Biology (Medical)',
            'Biochemistry and Molecular Biology (Executive program)': 'Biochemistry and Molecular Biology (Executive program) (Medical)',
            'Biology': 'Biology (Arts & Sciences)',
            'Biomedical Engineering': 'Biomedical Engineering (Engineering)',
            'Biostatistics': 'Biostatistics (Medical)',
            'Business': 'Business (Business)',
            'Cancer Biology': 'Cancer Biology (Medical)',
            'Cellular Physiology and Molecular Biophysics ': 'Cellular Physiology and Molecular Biophysics  (Medical)',
            'Chemical, Environmental, and Materials Engineering': 'Chemical, Environmental, and Materials Engineering (Engineering)',
            'Chemistry': 'Chemistry (Arts & Sciences)',
            'Choral Conducting': 'Choral Conducting (Music)',
            'Civil Engineering': 'Civil Engineering (Engineering)',
            'Communication': 'Communication (Communication)',
            'Community Well-Being': 'Community Well-Being (Education & Human Development)',
            'Composition': 'Composition (Music)',
            'Computer Science': 'Computer Science (Arts & Sciences)',
            'Counseling Psychology': 'Counseling Psychology (Education & Human Development)',
            'Economics': 'Economics (Business)',
            'Electrical and Computer Engineering': 'Electrical and Computer Engineering (Engineering)',
            'English': 'English (Arts & Sciences)',
            'Environmental Science and Policy ': 'Environmental Science and Policy  (RSMAS)',
            'Epidemiology': 'Epidemiology (Medical)',
            'Ergonomics': 'Ergonomics (Engineering)',
            'Exercise Physiology': 'Exercise Physiology (Education & Human Development)',
            'Higher Education Leadership': 'Higher Education Leadership (Education & Human Development)',
            'History': 'History (Arts & Sciences)',
            'Human Genetics and Genomics': 'Human Genetics and Genomics (Medical)',
            'Industrial Engineering': 'Industrial Engineering (Engineering)',
            'Instrumental Conducting': 'Instrumental Conducting (Music)',
            'Instrumental Jazz Performance': 'Instrumental Jazz Performance (Music)',
            'Instrumental Performance': 'Instrumental Performance (Music)',
            'International Studies': 'International Studies (Arts & Sciences)',
            'Jazz Composition': 'Jazz Composition (Music)',
            'Keyboard Performance': 'Keyboard Performance (Music)',
            'Keyboard Performance and Pedagogy': 'Keyboard Performance and Pedagogy (Music)',
            'Literary, Cultural, and Linguistic Studies': 'Literary, Cultural, and Linguistic Studies (Arts & Sciences)',
            'Marine Biology and Ecology': 'Marine Biology and Ecology (RSMAS)',
            'Marine Biology and Fisheries': 'Marine Biology and Fisheries (RSMAS)',
            'Marine Ecosystems and Society': 'Marine Ecosystems and Society (RSMAS)',
            'Marine Geology and Geophysics': 'Marine Geology and Geophysics (RSMAS)',
            'Marine Geosciences': 'Marine Geosciences (RSMAS)',
            'Mathematics': 'Mathematics (Arts & Sciences)',
            'Mechanical Engineering': 'Mechanical Engineering (Engineering)',
            'Meteorology and Physical Oceanography ': 'Meteorology and Physical Oceanography  (RSMAS)',
            'Microbiology and Immunology': 'Microbiology and Immunology (Medical)',
            'Molecular and Cellular Pharmacology': 'Molecular and Cellular Pharmacology (Medical)',
            'Molecular Cell and Developmental Biology': 'Molecular Cell and Developmental Biology (Medical)',
            'Multiple Woodwinds': 'Multiple Woodwinds (Music)',
            'Music Education': 'Music Education (Music)',
            'Neuroscience': 'Neuroscience (Medical)',
            'Nursing Science': 'Nursing Science (Nursing & Health Studies)',
            'Ocean Sciences': 'Ocean Sciences (RSMAS)',
            'Philosophy': 'Philosophy (Arts & Sciences)',
            'Physical Therapy': 'Physical Therapy (Medical)',
            'Physics': 'Physics (Arts & Sciences)',
            'Prevention Science and Community Health': 'Prevention Science and Community Health (Medical)',
            'Psychology': 'Psychology (Arts & Sciences)',
            'Research, Measurement and Evaluation': 'Research, Measurement and Evaluation (Education & Human Development)',
            'Romance Studies': 'Romance Studies (Arts & Sciences)',
            'Sociology': 'Sociology (Arts & Sciences)',
            'Teaching and Learning': 'Teaching and Learning (Education & Human Development)',
            'Vocal Jazz Performance': 'Vocal Jazz Performance (Music)',
            'Vocal Pedagogy and Performance': 'Vocal Pedagogy and Performance (Music)',
            'Vocal Performance': 'Vocal Performance (Music)'
        }
    },
    'masters': {
        'degreename': {
            'Master of Arts (MA)',
            'Master of Fine Arts (MFA)',
            'Master of Music (MM)',
            'Master of Science (MS)',
            'Master of Science in Architecture (MSArch)',
            'Master of Science in Education (MSEd)',
            'Master of Science in Architectural Engineering (MSAE)',
            'Master of Science in Biomedical Engineering (MSBE)',
            'Master of Science in Civil Engineering (MSCE)',
            'Master of Science in Electrical and Computer Engineering (MSECE)',
            'Master of Science in Industrial Engineering (MSIE)',
            'Master of Science in Mechanical Engineering (MSME)',
            'Master of Science in Ocean Engineering (MSOE)',
            'Master of Science in Public Health (MSPH)'
        },
        'degrees': {
            'Anthropology': 'Anthropology (Arts & Sciences)',
            'Applied Marine Physics': 'Applied Marine Physics (RSMAS)',
            'Architectural Engineering': 'Architectural Engineering (Engineering)',
            'Architecture: Architectural Studies Track ': 'Architecture: Architectural Studies Track  (Architecture)',
            'Atmospheric Sciences ': 'Atmospheric Sciences  (RSMAS)',
            'Biology': 'Biology (Arts & Sciences)',
            'Biomedical Engineering': 'Biomedical Engineering (Engineering)',
            'Cancer Biology': 'Cancer Biology (Medical)',
            'Chemistry': 'Chemistry (Arts & Sciences)',
            'Civil Engineering': 'Civil Engineering (Engineering)',
            'Climate and Health': 'Climate and Health (Medical)',
            'Communication Studies': 'Communication Studies (Communication)',
            'Community and Social Change': 'Community and Social Change (Education & Human Development)',
            'Computer Science': 'Computer Science (Arts & Sciences)',
            'Criminology and Criminal Justice': 'Criminology and Criminal Justice (Arts & Sciences)',
            'Electrical and Computer Engineering': 'Electrical and Computer Engineering (Engineering)',
            'English': 'English (Arts & Sciences)',
            'Environment, Culture, and Media': 'Environment, Culture, and Media (Graduate School - Abess programs)',
            'Geography': 'Geography (Arts & Sciences)',
            'Global Health and Society': 'Global Health and Society (Arts & Sciences)',
            'History': 'History (Arts & Sciences)',
            'Industrial Engineering': 'Industrial Engineering (Engineering)',
            'International Studies': 'International Studies (Arts & Sciences)',
            'Latin American Studies': 'Latin American Studies (Arts & Sciences)',
            'Liberal Studies': 'Liberal Studies (Arts & Sciences)',
            'Literary, Cultural, and Linguistic Studies': 'Literary, Cultural, and Linguistic Studies (Arts & Sciences)',
            'Marine Affairs and Policy': 'Marine Affairs and Policy (RSMAS)',
            'Marine Biology and Ecology': 'Marine Biology and Ecology (RSMAS)',
            'Marine Biology and Fisheries': 'Marine Biology and Fisheries (RSMAS)',
            'Marine Ecosystems and Society': 'Marine Ecosystems and Society (RSMAS)',
            'Marine Geology and Geophysics': 'Marine Geology and Geophysics (RSMAS)',
            'Marine Geosciences': 'Marine Geosciences (RSMAS)',
            'Mechanical Engineering': 'Mechanical Engineering (Engineering)',
            'Meteorology and Physical Oceanography': 'Meteorology and Physical Oceanography (RSMAS)',
            'Music Education': 'Music Education (Music)',
            'Music Therapy': 'Music Therapy (Music)',
            'Music Therapy with Undergraduate Equivalency': 'Music Therapy with Undergraduate Equivalency (Music)',
            'Musicology': 'Musicology (Music)',
            'Neuroscience': 'Neuroscience (Medical)',
            'Occupational Ergonomics and Safety': 'Occupational Ergonomics and Safety (Engineering)',
            'Ocean Engineering': 'Ocean Engineering (Engineering)',
            'Ocean Sciences ': 'Ocean Sciences  (RSMAS)',
            'Philosophy': 'Philosophy (Arts & Sciences)',
            'Physics': 'Physics (Arts & Sciences)',
            'Prevention Science and Community Health': 'Prevention Science and Community Health (Medical)',
            'Psychology': 'Psychology (Arts & Sciences)',
            'Public Health': 'Public Health (Medical)',
            'Public Relations': 'Public Relations (Communication)',
            'Skin Biology and Dermatological Sciences ': 'Skin Biology and Dermatological Sciences  (Medical)',
            'Sociology': 'Sociology (Arts & Sciences)'
        }
    },
    'languages': {
        'es': 'Spanish',
        'ar': 'Arabic',
        'zh': 'Chinese',
        'fr': 'French',
        'de': 'German',
        'hi': 'Hindi',
        'it': 'Italian',
        'ja': 'Japanese',
        'ko': 'Korean',
        'pt': 'Portuguese',
        'ru': 'Russian'
    },
    'topics': {
        'Fine and Performing Arts': {
            'Art criticism': '0365',
            'Art history': '0377',
            'Cinematography': '0435',
            'Dance': '0378',
            'Design': '0389',
            'Fashion': '0200',
            'Film studies': '0900',
            'Fine arts': '0357',
            'Music': '0413',
            'Music history': '0210',
            'Music theory': '0223',
            'Musical composition': '0216',
            'Musical performances': '0943',
            'Performing arts': '0641',
            'Theater': '0465',
            'Theater history': '0644'
        }
    },
    'grad_service_account': 'grad.dissertation@miami.edu',
    'grad_admin': 'dyamamoto@miami.edu',
    'repository_manager_email': 'j.cohen4@miami.edu',
    'app_admin': 'cgb37@miami.edu',
    'app_developer': 'eprieto502@miami.edu'
}